---
- name: Install dnsmasq
  ansible.builtin.apt:
    package:
      - dnsmasq
    state: present
    update_cache: true

- name: Create dnsmasq config
  ansible.builtin.template:
    src: "dnsmasq.conf.j2"
    dest: "/etc/dnsmasq.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: Restart dnsmasq

- name: Enable service dnsmasq
  ansible.builtin.systemd:
    daemon_reload: true
    name: dnsmasq.service
    state: started
    enabled: true
    masked: false
