---
- name: Install iptables
  ansible.builtin.apt:
    package:
      - iptables
      - netfilter-persistent
      - iptables-persistent
    state: present
    update_cache: true

- name: Create iptables rules
  ansible.builtin.template:
    src: "rules.v4.j2"
    dest: "/etc/iptables/rules.v4"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: Restart netfilter
